name: Check and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  NO_FIRMWARE_BIN: true

jobs:
  code_changed:
    name: Detect code changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      num_changed: ${{ steps.code_changed.outputs.count }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: code_changed
        run: |
          echo "count=$(git diff --name-only origin/main...HEAD | grep -e ^bin -e ^installer -e ^lib -e ^rootshell -e ^telcom-parser | wc -l)" >> "$GITHUB_OUTPUT"

  check_and_test:
    needs: code_changed
    if: ${{ steps.code_changed.outputs.num_changed != '0' }}
    strategy:
      matrix:
        device:
          - name: tplink
          - name: orbic
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: |
        pushd bin/web
        npm install
        npm run build
        popd
        cargo check --verbose --no-default-features --features=${{ matrix.device.name }}
    - name: Run tests
      run: |
        cargo test --verbose --no-default-features --features=${{ matrix.device.name }}
    - name: Run clippy
      run: cargo clippy --verbose --no-default-features --features=${{ matrix.device.name }}

  windows_installer_check_and_test:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: cargo check
        shell: bash
        run: |
          cd installer
          cargo check --verbose
      - name: cargo test
        shell: bash
        run: |
          cd installer
          cargo test --verbose --no-default-features --features=${{ matrix.device.name }}
