name: Release rayhunter
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  exist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Ensure all Cargo.toml files have the same version defined.
        run: |
          defined_versions=$(find lib bin installer rootshell telcom-parser -name Cargo.toml -exec grep ^version {} \; | uniq | wc -l)
          find lib bin installer rootshell telcom-parser -name Cargo.toml -exec grep ^version {} \;
          echo number of defined versions = $defined_versions
          if [ $defined_versions != "1" ]
          then
            echo "all Cargo.toml files must have the same version defined"
            exit 1
          fi
      - name: Create release
        run: |
          version=$(grep ^version lib/Cargo.toml | cut -d' ' -f3 | tr -d '"')
          gh release create $version
